version: '3.5'
services:
  web:
    networks:
      - localdb
    build: .
    volumes:
      - ./views:/app/views
    ports:
      - 1993:1993
    container_name: deno
    depends_on:
      - mongo
  mongo:
    networks:
      - localdb
    image: mongo
    restart: always
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    networks:
      - localdb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  localdb:
    driver: bridge
    name: localdb